### PR TITLE
casey-chow's application

### PR DESCRIPTION
**Pull request by casey-chow**
Requires Ruby 1.9.2+, though honestly any static server will suffice. Ruby's just happened to be the first one that worked for me reliably.

### CODE REVIEW

**Comment by drf-eng-apps** [comment]
Your application is invalid! The reason is: **challenge/run.sh did not output a URL with scheme http, https, ftp, or file

 output: 

 http://localhost:3143
**

**Comment by drf-eng-apps** [comment]
Your application is valid so far! :sunglasses:

If you have encrypted files, I'll check those for errors after @yasyf merges your application.

**Comment by drf-eng-apps** [comment]
Thanks @yasyf, your application has been fixed!

**Comment by yasyf** [comment]
hahaha this is incredible. cheers buddy. also thanks for pointing out the regex, its fixed ;)

**Pull request merged**
